### ISSUE TITLE
android端最近突然报错找不到符号  trackTimerBegin

### ISSUE THREAD

**Issue by shengbowen** [sensorsdata/react-native-sensors-analytics#22]
sensorsdata-analytics-react-native/android/src/main/java/com/sensorsdata/analytics/RNSensorsAnalyticsModule.java:146: 错误: 找不到符号LE
            SensorsDataAPI.sharedInstance().trackTimerBegin(eventName);
                                           ^
  符号:   方法 trackTimerBegin(String)
  位置: 类 SensorsDataAPI

之前一直都是好的。

"sensorsdata-analytics-react-native": "2.0.3"

**Comment by cr1106** [comment]
麻烦升级到 2.2.0 版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月26日(周二) 晚上7:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [sensorsdata/react-native-sensors-analytics] android端最近突然报错找不到符号  trackTimerBegin (Issue #22)




 
sensorsdata-analytics-react-native/android/src/main/java/com/sensorsdata/analytics/RNSensorsAnalyticsModule.java:146: 错误: 找不到符号LE
 SensorsDataAPI.sharedInstance().trackTimerBegin(eventName);
 ^
 符号:   方法 trackTimerBegin(String)
 位置: 类 SensorsDataAPI
 
之前一直都是好的。
 
"sensorsdata-analytics-react-native": "2.0.3"
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuweiqiang2016** [comment]
v2.2.0 已修复
